jobs:
- job: build
  pool:
    vmImage: 'macOS-10.15'

  variables:
    sdk: 'iphoneos'
    configuration: 'Release'
    workspace: 'Monica.xcworkspace'

  steps:
  - task: CocoaPods@0
    displayName: 'pod install'
    inputs:
      forceRepoUpdate: true
      projectDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Xcode@5
    displayName: Xcode build
    inputs:
      actions: 'clean build'
      sdk: '$(sdk)'
      scheme: 'Monica'
      configuration: '$(configuration)'
      xcodeVersion: 'default'
      xcWorkspacePath: '$(workspace)'

  - task: CopyFiles@2
    inputs:
      contents: |
        '**/*.ipa'
        '**/*.app'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1


- job: reporting
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: Sonarcloud
      organization: monicahq
      scannerMode: CLI
      configMode: manual
      cliProjectKey: 'monicahq_janice'
      cliProjectName: janice
      cliProjectVersion: 0.0

  - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
    displayName: 'Run Code Analysis'

  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'

